<template>
  <div class="space-y-6">

    <!-- Header -->
    <div class="flex items-center justify-between">
      <div>
        <h1 class="text-2xl font-bold text-white">QR Code History</h1>
        <p class="text-gray-400 mt-1">All payment QR codes generated by your account</p>
      </div>
      <button
        class="flex items-center gap-1.5 px-3 py-1.5 text-sm rounded-lg border border-slate-700 text-gray-400 hover:text-white hover:border-slate-500 transition-colors"
        @click="load()"
      >
        <svg class="w-4 h-4" :class="isLoading ? 'animate-spin' : ''" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" />
        </svg>
        Refresh
      </button>
    </div>

    <!-- Status filter tabs -->
    <div class="flex items-center gap-1 p-1 bg-slate-800/60 rounded-xl w-fit">
      <button
        v-for="tab in TABS"
        :key="tab.value"
        class="px-3 py-1.5 text-sm rounded-lg font-medium transition-colors"
        :class="activeStatus === tab.value
          ? 'bg-slate-700 text-white shadow'
          : 'text-gray-400 hover:text-gray-200'"
        @click="setStatus(tab.value)"
      >
        <span class="flex items-center gap-1.5">
          <span>{{ tab.icon }}</span>
          {{ tab.label }}
          <span
            v-if="tabCounts[tab.value] != null"
            class="px-1.5 py-0.5 rounded-full text-[10px] font-semibold"
            :class="tab.countClass"
          >{{ tabCounts[tab.value] }}</span>
        </span>
      </button>
    </div>

    <!-- Loading skeleton -->
    <template v-if="isLoading">
      <div v-for="i in 5" :key="i" class="h-16 rounded-xl bg-slate-800/60 animate-pulse" />
    </template>

    <!-- Empty state -->
    <div
      v-else-if="!records.length"
      class="flex flex-col items-center justify-center py-20 space-y-3"
    >
      <div class="w-14 h-14 rounded-2xl bg-slate-800 flex items-center justify-center text-2xl">
        {{ activeStatus === 'expired' ? '⏰' : activeStatus === 'paid' ? '✅' : '🔲' }}
      </div>
      <p class="text-white font-medium">No {{ activeStatus ?? '' }} QR codes found</p>
      <p class="text-gray-500 text-sm">
        {{ activeStatus === 'expired'
          ? 'No expired QR codes — all good!'
          : 'Generate a QR code from the Payments page to get started.' }}
      </p>
      <NuxtLink
        to="/payments"
        class="flex items-center gap-1.5 px-3 py-1.5 text-sm rounded-lg border border-indigo-500/40 text-indigo-300 hover:bg-indigo-500/10 transition-colors"
      >
        Go to Payments
      </NuxtLink>
    </div>

    <!-- Records table -->
    <template v-else>
      <div class="rounded-xl border border-slate-700/50 overflow-hidden">
        <!-- Table header -->
        <div class="grid grid-cols-[1fr_1fr_auto_auto_auto] gap-4 px-4 py-2.5 bg-slate-800/80 text-xs font-semibold text-gray-400 uppercase tracking-wider border-b border-slate-700/50">
          <span>QR / Order</span>
          <span>Amount</span>
          <span>Status</span>
          <span>Created · Expires</span>
          <span></span>
        </div>

        <!-- Rows -->
        <div class="divide-y divide-slate-700/40">
          <div
            v-for="rec in records"
            :key="rec.qrId"
            class="grid grid-cols-[1fr_1fr_auto_auto_auto] gap-4 items-center px-4 py-3 hover:bg-slate-800/40 transition-colors"
          >
            <!-- IDs -->
            <div class="min-w-0">
              <p class="text-xs font-mono text-gray-300 truncate" :title="rec.qrId">
                {{ shortId(rec.qrId) }}
              </p>
              <NuxtLink
                :to="`/payments`"
                class="text-[11px] font-mono text-indigo-400 hover:text-indigo-300 truncate block"
                :title="rec.orderId"
              >
                order {{ shortId(rec.orderId) }}
              </NuxtLink>
            </div>

            <!-- Amount -->
            <div>
              <span class="text-sm font-semibold text-white">
                {{ formatAmount(rec.amount) }}
              </span>
              <span class="text-xs text-gray-500 ml-1">{{ rec.currency }}</span>
            </div>

            <!-- Status badge -->
            <QrStatusBadge :status="rec.status" />

            <!-- Timestamps -->
            <div class="text-right space-y-0.5">
              <p class="text-xs text-gray-400">{{ formatDate(rec.createdAt) }}</p>
              <!-- Relative duration line — updates every minute via `now` tick -->
              <p class="text-[11px]" :class="durationClass(rec)">
                {{ durationLabel(rec) }}
              </p>
            </div>

            <!-- Action -->
            <div class="flex justify-end">
              <!-- Expired → offer to regenerate on the payments page -->
              <NuxtLink
                v-if="rec.status === 'expired'"
                :to="`/payments?regenerate=${rec.orderId}`"
                class="px-2.5 py-1 text-xs rounded-lg border border-amber-500/30 text-amber-400 hover:bg-amber-500/10 transition-colors whitespace-nowrap"
              >
                Regenerate QR
              </NuxtLink>
              <!-- Pending → fetch QR detail and open inline modal -->
              <button
                v-else-if="rec.status === 'pending'"
                :disabled="isLoadingQr && loadingQrId === rec.qrId"
                class="flex items-center gap-1 px-2.5 py-1 text-xs rounded-lg border border-indigo-500/30 text-indigo-400 hover:bg-indigo-500/10 transition-colors disabled:opacity-50"
                @click="openQrForRecord(rec.qrId)"
              >
                <svg
                  v-if="isLoadingQr && loadingQrId === rec.qrId"
                  class="w-3 h-3 animate-spin"
                  fill="none"
                  viewBox="0 0 24 24"
                >
                  <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4" />
                  <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
                </svg>
                View QR
              </button>
            </div>
          </div>
        </div>
      </div>

      <!-- Pagination -->
      <div v-if="total > limit" class="flex items-center justify-between text-sm">
        <span class="text-gray-500">
          Showing {{ skip + 1 }}–{{ Math.min(skip + limit, total) }} of {{ total }}
        </span>
        <div class="flex gap-2">
          <button
            :disabled="skip === 0"
            class="px-3 py-1.5 rounded-lg border border-slate-700 text-gray-400 hover:text-white disabled:opacity-30 transition-colors"
            @click="prevPage"
          >
            ← Prev
          </button>
          <button
            :disabled="skip + limit >= total"
            class="px-3 py-1.5 rounded-lg border border-slate-700 text-gray-400 hover:text-white disabled:opacity-30 transition-colors"
            @click="nextPage"
          >
            Next →
          </button>
        </div>
      </div>
    </template>

    <!-- Inline QR Modal — opened from the "View QR" button in the table -->
    <QrModal
      v-if="activeDetail"
      :model-value="showQrModal"
      :qr="{ qrId: activeDetail.qrId, qrImage: activeDetail.qrImage ?? '', expiresAt: activeDetail.expiresAt, amount: activeDetail.amount }"
      :status="activeDetail.status"
      :seconds-left="activeDetail.secondsLeft"
      @close="handleQrClose"
      @regenerate="handleQrRegenerate"
      @paid="handleQrPaid"
    />

  </div>
</template>

<script setup lang="ts">
import type { PaymentQrDetail, PaymentQrStatus, QrHistoryRecord } from '~/types'

definePageMeta({ middleware: 'auth' })

const router = useRouter()
const { paymentsApi } = useApi()

// ── Filter tabs ────────────────────────────────────────────────────────────────

const TABS = [
  { value: undefined,   label: 'All',      icon: '🔲', countClass: 'bg-slate-600 text-gray-200' },
  { value: 'pending',   label: 'Pending',  icon: '⏳', countClass: 'bg-indigo-500/20 text-indigo-300' },
  { value: 'paid',      label: 'Paid',     icon: '✅', countClass: 'bg-emerald-500/20 text-emerald-300' },
  { value: 'expired',   label: 'Expired',  icon: '⏰', countClass: 'bg-rose-500/20 text-rose-300' },
  { value: 'cancelled', label: 'Cancelled',icon: '🚫', countClass: 'bg-slate-600 text-gray-400' },
] as const

type TabValue = (typeof TABS)[number]['value']

const activeStatus = ref<TabValue>(undefined)

// Tab counts — loaded once for the "All" totals, then per-status lazily
const tabCounts = reactive<Record<string, number | undefined>>({})

// ── Pagination ─────────────────────────────────────────────────────────────────

const skip  = ref(0)
const limit = 20

// ── Data ───────────────────────────────────────────────────────────────────────

const records   = ref<QrHistoryRecord[]>([])
const total     = ref(0)
const isLoading = ref(false)

async function load() {
  isLoading.value = true
  try {
    const params: Record<string, unknown> = { skip: skip.value, limit }
    if (activeStatus.value) params.status = activeStatus.value

    const result = await paymentsApi.getQrHistory(params)
    records.value = result.data
    total.value   = result.total

    // Update tab count for the active filter
    const key = activeStatus.value ?? 'all'
    tabCounts[key] = result.total
  } finally {
    isLoading.value = false
  }
}

function setStatus(val: TabValue) {
  activeStatus.value = val
  skip.value = 0
  void load()
}

function nextPage() {
  skip.value += limit
  void load()
}

function prevPage() {
  skip.value = Math.max(0, skip.value - limit)
  void load()
}

// ── Live clock for relative durations ─────────────────────────────────────────

// Ticks every 30 seconds so "expires in X" / "expired X ago" stays fresh
const now = ref(Date.now())
let clockTimer: ReturnType<typeof setInterval> | null = null

// ── Formatters ─────────────────────────────────────────────────────────────────

function shortId(id: string) {
  return `#${id.slice(-6).toUpperCase()}`
}

function formatAmount(n: number) {
  return new Intl.NumberFormat('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(n)
}

function formatDate(iso: string | null | undefined): string {
  if (!iso) return '—'
  return new Date(iso).toLocaleString('en-US', { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' })
}

/**
 * Returns a human-readable relative duration string for a record's time column.
 * Reacts to the `now` tick so values update without a page reload.
 */
function durationLabel(rec: QrHistoryRecord): string {
  // Reference `now.value` so Vue tracks the dependency and re-renders on each tick
  const _ = now.value

  if (rec.status === 'paid' && rec.paidAt) {
    return `Paid ${timeAgo(rec.paidAt)}`
  }
  if (rec.status === 'expired') {
    return `Expired ${timeAgo(rec.expiresAt)}`
  }
  if (rec.status === 'pending') {
    const diffMs = new Date(rec.expiresAt).getTime() - now.value
    if (diffMs <= 0) return 'Expiring now…'
    return `Expires in ${formatDuration(diffMs)}`
  }
  return `Exp. ${formatDate(rec.expiresAt)}`
}

function durationClass(rec: QrHistoryRecord): string {
  if (rec.status === 'expired') return 'text-rose-400 font-medium'
  if (rec.status === 'paid')    return 'text-emerald-400'
  if (rec.status === 'pending') {
    const diffMs = new Date(rec.expiresAt).getTime() - now.value
    return diffMs < 60_000 ? 'text-amber-400 font-medium' : 'text-gray-500'
  }
  return 'text-gray-600'
}

/** "5 minutes ago", "2 hours ago", "3 days ago" */
function timeAgo(iso: string | null | undefined): string {
  if (!iso) return ''
  const diffMs  = now.value - new Date(iso).getTime()
  const diffSec = Math.abs(Math.floor(diffMs / 1000))

  if (diffSec < 60)        return `${diffSec}s ago`
  if (diffSec < 3600)      return `${Math.floor(diffSec / 60)}m ago`
  if (diffSec < 86400)     return `${Math.floor(diffSec / 3600)}h ago`
  return `${Math.floor(diffSec / 86400)}d ago`
}

/** "9m 30s", "1h 5m", "2d 3h" — for countdown-style remaining time */
function formatDuration(ms: number): string {
  const totalSec = Math.floor(ms / 1000)
  if (totalSec < 60)       return `${totalSec}s`
  if (totalSec < 3600) {
    const m = Math.floor(totalSec / 60)
    const s = totalSec % 60
    return s > 0 ? `${m}m ${s}s` : `${m}m`
  }
  if (totalSec < 86400) {
    const h = Math.floor(totalSec / 3600)
    const m = Math.floor((totalSec % 3600) / 60)
    return m > 0 ? `${h}h ${m}m` : `${h}h`
  }
  const d = Math.floor(totalSec / 86400)
  const h = Math.floor((totalSec % 86400) / 3600)
  return h > 0 ? `${d}d ${h}h` : `${d}d`
}

// ── Inline QR modal ────────────────────────────────────────────────────────────

const activeDetail  = ref<PaymentQrDetail | null>(null)
const showQrModal   = ref(false)
const isLoadingQr   = ref(false)
const loadingQrId   = ref<string | null>(null)

async function openQrForRecord(qrId: string) {
  isLoadingQr.value = true
  loadingQrId.value = qrId
  try {
    const detail = await paymentsApi.getQr(qrId)
    if (detail) {
      activeDetail.value = detail
      showQrModal.value  = true
    }
  } finally {
    isLoadingQr.value = false
    loadingQrId.value = null
  }
}

function handleQrClose() {
  showQrModal.value  = false
  activeDetail.value = null
}

function handleQrRegenerate() {
  if (!activeDetail.value) return
  const orderId = activeDetail.value.orderId
  handleQrClose()
  void router.push(`/payments?regenerate=${orderId}`)
}

function handleQrPaid() {
  if (activeDetail.value) {
    // Optimistically reflect paid status in the table row
    const rec = records.value.find(r => r.qrId === activeDetail.value!.qrId)
    if (rec) rec.status = 'paid'
  }
  handleQrClose()
}

onMounted(() => {
  void load()
  clockTimer = setInterval(() => { now.value = Date.now() }, 30_000)
})

onUnmounted(() => {
  if (clockTimer !== null) clearInterval(clockTimer)
})
</script>
